import { env } from "cloudflare:workers";
import { hasNameEntitlement } from "./nameStyles";
export const HEX=/^#[0-9A-F]{6}$/;
export type StyleMode="NONE"|"COLOR"|"GRADIENT"|"RAINBOW";
export type Gradient={stops:{color:string;position:number}[];smooth:boolean;direction:"LEFT_TO_RIGHT"|"RIGHT_TO_LEFT"};
export type Rainbow={speed:number;saturation:number;brightness:number;direction:"LEFT_TO_RIGHT"|"RIGHT_TO_LEFT"};
export function normalizeHex(value:unknown){const raw=String(value??"").trim().toUpperCase();const color=raw.startsWith("#")?raw:`#${raw}`;return HEX.test(color)?color:null}
export function validateGradient(value:unknown):Gradient|null{if(!value||typeof value!=="object")return null;const v=value as Record<string,unknown>;if(!Array.isArray(v.stops)||v.stops.length<2||v.stops.length>5)return null;const stops=v.stops.map(s=>{const x=s as Record<string,unknown>;return {color:normalizeHex(x.color),position:Number(x.position)}});if(stops.some(s=>!s.color||!Number.isFinite(s.position)||s.position<0||s.position>1))return null;for(let i=1;i<stops.length;i++)if(stops[i].position<=stops[i-1].position)return null;const direction=v.direction==="RIGHT_TO_LEFT"?"RIGHT_TO_LEFT":"LEFT_TO_RIGHT";return {stops:stops as Gradient["stops"],smooth:v.smooth!==false,direction}}
export function validateRainbow(value:unknown):Rainbow|null{if(!value||typeof value!=="object")return null;const v=value as Record<string,unknown>;const speed=Number(v.speed),saturation=Number(v.saturation),brightness=Number(v.brightness);if(!Number.isFinite(speed)||speed<0.1||speed>5||!Number.isFinite(saturation)||saturation<0.2||saturation>1||!Number.isFinite(brightness)||brightness<0.2||brightness>1)return null;return {speed,saturation,brightness,direction:v.direction==="RIGHT_TO_LEFT"?"RIGHT_TO_LEFT":"LEFT_TO_RIGHT"}}
export async function capabilities(userId:string){
 const [color,gradient,rainbow,glyph,tags]=await Promise.all([hasNameEntitlement(userId,"NAME_COLOR_CUSTOM"),hasNameEntitlement(userId,"NAME_GRADIENT"),hasNameEntitlement(userId,"NAME_RAINBOW"),hasNameEntitlement(userId,"NAME_GLYPH"),env.DB.prepare("SELECT t.id,t.display_text,t.prefix,t.suffix,t.color FROM user_tags u JOIN cosmetic_tags t ON t.id=u.tag_id WHERE u.user_id=? AND t.available=1 AND (u.expires_at IS NULL OR u.expires_at>?)").bind(userId,Date.now()).all<Record<string,string>>()]);
 return {nameStyles:{color,gradient,rainbow},glyph,tags:tags.results};
}
export async function enforceFallback(userId:string){const caps=await capabilities(userId);const row=await env.DB.prepare("SELECT name_style_mode,active_tag FROM users WHERE id=?").bind(userId).first<Record<string,string>>();const mode=String(row?.name_style_mode??"NONE");const allowed=mode==="COLOR"?caps.nameStyles.color:mode==="GRADIENT"?caps.nameStyles.gradient:mode==="RAINBOW"?caps.nameStyles.rainbow:true;const tagOk=!row?.active_tag||caps.tags.some(t=>t.id===row.active_tag);if(!allowed||!tagOk)await env.DB.prepare("UPDATE users SET name_style_mode=?,active_tag=? WHERE id=?").bind(allowed?mode:"NONE",tagOk?row?.active_tag:null,userId).run();return capabilities(userId)}
