import { env } from "cloudflare:workers";

export const ORDER_STATUSES=new Set(["PENDING","PAID","FAILED","CANCELED","REFUNDED"]);
export type StoreProduct=Record<string,string|number|null>;
export async function rateLimit(key:string,limit:number,windowMs:number){const now=Date.now(),start=now-windowMs;await env.DB.prepare("DELETE FROM api_rate_limits WHERE window_start<?").bind(start).run();const row=await env.DB.prepare("SELECT window_start,count FROM api_rate_limits WHERE key=?").bind(key).first<{window_start:number;count:number}>();if(!row||row.window_start<start){await env.DB.prepare("INSERT OR REPLACE INTO api_rate_limits VALUES (?,?,1)").bind(key,now).run();return true}if(row.count>=limit)return false;await env.DB.prepare("UPDATE api_rate_limits SET count=count+1 WHERE key=?").bind(key).run();return true}
export async function audit(actor:string|null,action:string,targetType:string,targetId:string,detail:unknown={}){await env.DB.prepare("INSERT INTO store_audit_log VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),actor,action,targetType,targetId,JSON.stringify(detail),Date.now()).run()}
export async function activeEntitlements(userId:string){const now=Date.now();return env.DB.prepare("SELECT id,type,resource_id,source,source_id,granted_at,expires_at,metadata_json FROM entitlements WHERE user_id=? AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at>?) ORDER BY granted_at DESC").bind(userId,now).all<Record<string,string|number|null>>()}
export async function grantProduct(userId:string,productId:string,source:"PURCHASE"|"SUBSCRIPTION"|"EVENT"|"GIFT"|"STAFF"|"SYSTEM",sourceId:string,expiresAt:number|null){const product=await env.DB.prepare("SELECT id,type,entitlement_key,metadata_json FROM products WHERE id=?").bind(productId).first<Record<string,string>>();if(!product)throw new Error("PRODUCT_NOT_FOUND");const existing=await env.DB.prepare("SELECT id FROM entitlements WHERE user_id=? AND type=? AND resource_id=? AND source=? AND source_id=?").bind(userId,product.type,product.id,source,sourceId).first<{id:string}>();if(existing)return existing.id;const id=crypto.randomUUID(),now=Date.now();await env.DB.prepare("INSERT INTO entitlements (id,user_id,type,resource_id,source,source_id,granted_at,expires_at,revoked_at,metadata_json) VALUES (?,?,?,?,?,?,?,?,NULL,?)").bind(id,userId,product.type,product.id,source,sourceId,now,expiresAt,product.metadata_json||"{}").run();await env.DB.prepare("INSERT OR IGNORE INTO user_entitlements (id,user_id,entitlement_key,source,expires_at,created_at) VALUES (?,?,?,?,?,?)").bind(id,userId,product.entitlement_key,source,expiresAt,now).run();if(product.type==="CUSTOM_TAG"){const metadata=JSON.parse(product.metadata_json||"{}");if(metadata.tagId)await env.DB.prepare("INSERT OR REPLACE INTO user_tags VALUES (?,?,?,?,?)").bind(userId,metadata.tagId,source,expiresAt,now).run()}await audit(userId,"ENTITLEMENT_GRANTED","product",productId,{source,sourceId,expiresAt});return id}
export async function revokeOrderEntitlements(orderId:string){await env.DB.prepare("UPDATE entitlements SET revoked_at=? WHERE source='PURCHASE' AND source_id=? AND revoked_at IS NULL").bind(Date.now(),orderId).run();await env.DB.prepare("DELETE FROM user_entitlements WHERE source='PURCHASE' AND id IN (SELECT id FROM entitlements WHERE source_id=?)").bind(orderId).run()}
export async function activateOrder(orderId:string,providerPaymentId:string){const order=await env.DB.prepare("SELECT * FROM orders WHERE id=?").bind(orderId).first<Record<string,string|number|null>>();if(!order)throw new Error("ORDER_NOT_FOUND");if(order.status==="PAID")return;if(order.status!=="PENDING")throw new Error("ORDER_NOT_PENDING");await env.DB.prepare("UPDATE orders SET status='PAID',provider_payment_id=?,paid_at=? WHERE id=? AND status='PENDING'").bind(providerPaymentId,Date.now(),orderId).run();if(order.product_id)await grantProduct(String(order.user_id),String(order.product_id),"PURCHASE",orderId,null);if(order.plan_id){const end=Date.now()+30*24*60*60*1000;const subscriptionId=crypto.randomUUID();await env.DB.prepare("INSERT INTO subscriptions VALUES (?,?,?,?,?,?,?,?)").bind(subscriptionId,order.user_id,order.plan_id,"ACTIVE",Date.now(),end,0,Date.now()).run();const products=await env.DB.prepare("SELECT product_id FROM plan_products WHERE plan_id=?").bind(order.plan_id).all<{product_id:string}>();for(const item of products.results)await grantProduct(String(order.user_id),item.product_id,"SUBSCRIPTION",subscriptionId,end)}await audit(String(order.user_id),"ORDER_PAID","order",orderId,{providerPaymentId})}
export async function isAdmin(userId:string){const row=await env.DB.prepare("SELECT is_admin FROM users WHERE id=?").bind(userId).first<{is_admin:number}>();return row?.is_admin===1}
export function safeJson(value:string|null|undefined){try{return JSON.parse(value||"{}")}catch{return {}}}
